---
- name: Deploy Calculator Container
  hosts: localhost
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "nikxdomain/calculator"
        source: pull
      register: docker_pull_result

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Run Calculator Container
      shell: docker run -it -d --name calculator nikxdomain/calculator


